language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:travis || travis_terminate 1;
  fi
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
env:
  global:
  - SAUCE_USERNAME: D2L_Stardust_UX_Chapter
  - REPO_NAME=pagination
  - OWNER_NAME=BrightspaceUILabs
  # SAUCE_ACCESS_KEY
  - secure: X7LEF2Ihq0uYv6VO32xeD8UOM1kEu8GOpAH2OgMkniKTdfM636xWlGe729npR0f27Y/TJjQZjj9fE9WDn1eH+RLW+BWKYpoF+bU8VMUrlsa2p+9qbFaDf4DYHzKM0ls7hMq5wgoFwEorTsEOm6wF4Jvhsk6rB+A5S2JMk80jZDWU8QWz5yiD3C0DwzHDvlrb2EajkSlvPQ+pXHjR+3Vep0pjf14N0vq26PjvKWElBKrjb/hNcWwf7Dxcg5+pBm6/V/CvtOb13wv/7k4As2vZj92L3uSDBgnCkh0fi7srRajCN6Fn4EeBuSBFbUwgbgXRmhm98xZ39L5L2pm8+cmDQ1qe+sDCeP/M3jBYxgz/HlV2k1oNG45owJWvQqtNZD49s7KBkfjVP1zbY6ZaYKiMbCf0HOPIFOTFjgkSM0f0PsOLdvtZxreMlppO/nZvEgIT67bx2QccZvS680spuZshQWq4i59rhZHgmPSLvBveK6lSr7NKrNV+2ScV18unIaAW5eTZxMlKJxF0pp7c9uTfzTNEh5ifzSqfVsOP1dAmjKvmFaD3O3pKjXMlUCPU8eT8ReELw/O0KnwX/loTqkgqliKsXiZnm2G6qKmjdutoOudFcSCRV7zjL1lHXOMeqwf0WauysOm+G5zmrAf5KwCV0NezmNF25YItaa3lniA6BQ0=
  # GITHUB_RELEASE_TOKEN (9f3f......d202)
  - secure: eX6hP0UoFw8Jhu6pm8KxUvZK/ru5FiDzn2C1JbwBHoUZGOp2So2KPShJV3EUI/ZNC+vFAInOf8rmQOYZhYQAqdxkXKZbXpBFJHLmfwmPk25ZRRubs/sDraUqaOOuyL2eYEbl5a4YU+KRAoLZZNtueh+XDynf7EGqN3CNfR2Hs2UnVqLME0/77xPMN2C/ya640z5GgvNrWChmkqu3tMvuDmNln5bAOSkEpfj/qhovfjUhIq7xhL0jQol1iQOqxD5wmTyg0E1fjxBgutInp7GoCK33yy7Mq4iHYTeI4chRN/TKaANM/TETc9sTiaboAkEi7al3NkAiWpuFy7taIWlMDt+FckH75nwQIZGXDlOHoBWl4fud2FmZBPMR0rzqFSN65mVhjUUH9IqR4Lb0TptkWPEJyKCNqvdHcu2ej40RZwDXhc5ksbALJXwtnLIkQVrU/Rrd8S/llvFBu1U64/dhphMbD2D7Cf98aySgQpTifuz+y+bVDy7pyWyw6+vKNm6iz0JwyQVjwZpmBiSYn83Gc71o9YlYpdEBxvYoTa5pYSyBRVak8LpNwx+P2yiTPxDQb1oKJJmYxS967c4TwicebZEBaRICoH69Rf05BD1/+fp7I1LbNFWz22hB+mneKorwW99A7sgj0L7FtXSIQI7oeaCvy3GZ5GrAg1x/ki0g+bE=
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # 64d0.........f1f7
    secure: mJG5AMpZdUwjQ9utlBKD/jkr3vj8dSg6g1WtSgYL5iRyXcJixz7BbfCKAbDmnGyvJQRDNq+Z7LkhZJByOaAZrHDn8IMIJGO5JXSWPC6z5hjIlQyXeLUE5lXRQR3HUeN5GlYJLeIfxXBMl4iO2WwtRMagIhVslk0titJYk0tRJvgfo3x7IAtFL+DSnkL50Q6ub3TsEnPZ2Jh2K6wTGFxmqydNFUot77USPcQhtXD1J1piSLJhuHHj5+qDzqR//hUxWiJP49pyY71yX5PxC9ftvO1LjML+tk/Rum/2KM5et+r1RrgLXkKcKU1seiOxHIWE/0wjNLMFciSh9YbmgC4rOIIEy2l83StX/HuOUQsidWRbeWZFxihbDCS/tex4sOkhFBz9j7LiF9aQsa6aBJyiupiwJj3v/2lUwROOQOGFCPwjJ3DfCJpkn5HIyBDtSP1yXlr4GtgwB2T3v/2hjWdXWXNxeFnioQFSWQqV6BylEmfvr8yHKjivfgG+H5x49WGCa2GOLMlgZqqSmZvt34oD8oaM3k6jGvlQyJ8RXJ9ogXzyx/Bk6SNjWPvISl+jKrOF6E/A+o5TCRM3skVLjbagT/HJo/qED7BLbhsM/316qCAMYR6ziOBEwkXHayPV3z5jQmQQ8GHGOLUsVjXLbv0r6HXcWNaiEVQC5n+UZYPQJEA=
  on:
    tags: true
    repo: BrightspaceUILabs/pagination
